# Generated by Django 3.0.5 on 2020-04-11 16:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(blank=True, editable=False, null=True)),
                ('oracle_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('uri', models.URLField(blank=True, max_length=500, null=True)),
                ('scryfall_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('image_uris', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('mana_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('cmc', models.IntegerField(blank=True, null=True)),
                ('colors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('type_line', models.CharField(blank=True, max_length=255, null=True)),
                ('color_identity', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('reserved', models.BooleanField(blank=True, default=False, null=True)),
                ('nonfoil', models.BooleanField(blank=True, default=False, null=True)),
                ('promo', models.BooleanField(blank=True, default=False, null=True)),
                ('reprint', models.BooleanField(blank=True, default=False, null=True)),
                ('variation', models.BooleanField(blank=True, default=False, null=True)),
                ('set', models.CharField(db_column='set', max_length=255)),
                ('set_name', models.CharField(blank=True, db_column='set_name', max_length=255, null=True)),
                ('set_type', models.CharField(blank=True, db_column='set_type', max_length=255, null=True)),
                ('set_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('set_search_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('scryfall_set_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('rulings_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('prints_search_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('collector_number', models.CharField(blank=True, max_length=255, null=True)),
                ('digital', models.CharField(blank=True, max_length=255, null=True)),
                ('rarity', models.CharField(blank=True, max_length=255, null=True)),
                ('full_art', models.BooleanField(blank=True, default=False, null=True)),
                ('textless', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'DeckPocket_Card',
            },
        ),
    ]
