# Generated by Django 3.0.5 on 2020-04-25 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckpocketuser',
            name='id',
        ),
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='updated',
            field=models.DateTimeField(blank=True, db_column='updated', null=True),
        ),
        migrations.AddField(
            model_name='deckpocketuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deckpocketuser',
            name='updated',
            field=models.DateTimeField(blank=True, db_column='updated', null=True),
        ),
        migrations.AddField(
            model_name='deckpocketuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, db_column='updated', null=True)),
                ('deck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('deck_type', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='campaign_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_user', to='deck_pocket.DeckPocketUser')),
            ],
            options={
                'db_table': 'Deck',
            },
        ),
    ]
