# Generated by Django 3.0.5 on 2020-04-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0003_auto_20200425_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.AddField(
            model_name='deck',
            name='user_deck',
            field=models.ForeignKey(blank=True, db_column='user_deck', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_user', to='deck_pocket.DeckPocketUser'),
        ),
    ]
