# Generated by Django 3.0.5 on 2020-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0004_auto_20200425_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(db_column='cards', db_table='DeckCard', related_name='deck_cards', to='deck_pocket.Card'),
        ),
    ]
