# Generated by Django 3.0.5 on 2020-05-03 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0005_deck_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, db_column='updated', null=True)),
                ('whishlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', default='Whishlist', max_length=255, null=True)),
                ('cards', models.ManyToManyField(db_column='cards', db_table='WhishlistCard', related_name='whish_cards', to='deck_pocket.Card')),
                ('user_whishlist', models.ForeignKey(blank=True, db_column='user_whishlist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_whishlist', to='deck_pocket.DeckPocketUser')),
            ],
            options={
                'db_table': 'Whishlist',
            },
        ),
        migrations.CreateModel(
            name='MyCards',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, db_column='updated', null=True)),
                ('my_cards_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', default='MyCards', max_length=255, null=True)),
                ('cards', models.ManyToManyField(db_column='cards', db_table='MyCard', related_name='my_cards', to='deck_pocket.Card')),
                ('user_cards', models.ForeignKey(blank=True, db_column='user_cards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to='deck_pocket.DeckPocketUser')),
            ],
            options={
                'db_table': 'MyCards',
            },
        ),
    ]
