# Generated by Django 3.0.6 on 2020-05-18 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0009_auto_20200517_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCards',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(blank=True, db_column='updated', null=True)),
                ('group_card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', default='MyCards', max_length=255, null=True)),
                ('deck', models.ForeignKey(blank=True, db_column='deck_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grouped_cards', to='deck_pocket.Deck')),
            ],
            options={
                'db_table': 'GroupCards',
            },
        ),
        migrations.AddField(
            model_name='cardfordeck',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_card', to='deck_pocket.GroupCards'),
        ),
    ]
