# Generated by Django 3.0.6 on 2020-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0010_auto_20200518_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mkm_url',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
