# Generated by Django 3.0.7 on 2020-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0011_card_mkm_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='cards',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='deck_id',
            field=models.ManyToManyField(db_column='deck_id', db_table='WhishlistDecks', related_name='whish_decks', to='deck_pocket.Deck'),
        ),
    ]
