# Generated by Django 3.0.7 on 2020-07-05 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0012_auto_20200705_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(blank=True, db_column='updated', null=True)),
                ('wish_list_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', default='Wishlist', max_length=255, null=True)),
                ('deck_id', models.ManyToManyField(db_column='deck_id', db_table='WishlistDecks', related_name='wish_decks', to='deck_pocket.Deck')),
                ('user_whishlist', models.ForeignKey(blank=True, db_column='user_wishlist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to='deck_pocket.DeckPocketUser')),
            ],
            options={
                'db_table': 'WishList',
            },
        ),
        migrations.DeleteModel(
            name='Whishlist',
        ),
    ]
