# Generated by Django 3.0.7 on 2020-07-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0013_auto_20200705_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_whishlist',
            new_name='user_wishlist',
        ),
    ]
