# Generated by Django 3.0.7 on 2020-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0015_auto_20200705_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycards',
            name='cards',
        ),
        migrations.AddField(
            model_name='mycards',
            name='deck_id',
            field=models.ManyToManyField(db_column='deck_id', db_table='MyCard', related_name='my_cards', to='deck_pocket.Deck'),
        ),
    ]
