# Generated by Django 3.0.7 on 2020-07-26 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0016_auto_20200705_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='MkmLink',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(blank=True, db_column='updated', null=True)),
                ('mkm_link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clicked', models.BigIntegerField(blank=True, null=True)),
                ('card_id', models.ForeignKey(blank=True, db_column='card_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_card', to='deck_pocket.Card')),
            ],
            options={
                'db_table': 'MkmLink',
            },
        ),
    ]
