# Generated by Django 3.0.7 on 2020-07-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0018_deck_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='budget_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards_had',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards_needed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='total_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
