# Generated by Django 3.0.7 on 2020-09-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0020_auto_20200812_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lang',
            field=models.CharField(blank=True, db_column='lang', max_length=255, null=True),
        ),
    ]
