# Generated by Django 3.0.7 on 2020-09-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_pocket', '0021_card_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='printed_name',
            field=models.CharField(blank=True, db_column='printed_name', max_length=255, null=True),
        ),
    ]
